[versions]
androidGradlePlugin= "8.13.2"
annotation="1.9.1"
appcompat="1.7.1"
constraintlayout="2.2.1"
espresso="3.7.0"
junit="1.3.0"
kotlin="2.3.0"

[libraries]
android-annotation={module="androidx.annotation:annotation", version.ref = "annotation" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
espresso-core={module="androidx.test.espresso:espresso-core", version.ref = "espresso"}
junit= {module = "androidx.test.ext:junit", version.ref = "junit" }


[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
