[versions]
androidGradlePlugin="8.11.1"
annotation="1.9.1"
espresso="3.6.1"
junit="1.2.1"
kotlin="2.2.21"

[libraries]
android-annotation={module="androidx.annotation:annotation", version.ref = "annotation" }
espresso-core={module="androidx.test.espresso:espresso-core", version.ref = "espresso"}
junit= {module = "androidx.test.ext:junit", version.ref = "junit" }


[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
